dreamwalker:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  shoulder_joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_joint1
    pid: {p: 1.0, i: 0.50, d: 0.0}
  shoulder_joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_joint2
    pid: {p: 1.0, i: 0.50, d: 0.0}
  shoulder_joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_joint3
    pid: {p: 1.0, i: 0.50, d: 0.0}
  shoulder_joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_joint4
    pid: {p: 1.0, i: 0.50, d: 0.0}
  limb_joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: limb_joint1
    pid: {p: 1.0, i: 0.00, d: 0.0}
  limb_joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: limb_joint2
    pid: {p: 1.0, i: 0.00, d: 0.0}
  limb_joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: limb_joint3
    pid: {p: 1.0, i: 0.00, d: 0.0}
  limb_joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: limb_joint4
    pid: {p: 1.0, i: 0.00, d: 0.0}
  knee_joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: knee_joint1
    pid: {p: 1.0, i: 0.00, d: 0.0}
  knee_joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: knee_joint2
    pid: {p: 1.0, i: 0.00, d: 0.0}
  knee_joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: knee_joint3
    pid: {p: 1.0, i: 0.00, d: 0.0}
  knee_joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: knee_joint4
    pid: {p: 1.0, i: 0.00, d: 0.0}
